name: Daily Heartbeat Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update heartbeat file
        run: echo "Last update: $(date -u)" > heartbeat.txt

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add heartbeat.txt
          git commit -m "chore: automated heartbeat [skip ci]" || echo "No changes to commit"
          git push
